apiVersion: v1
kind: Namespace
metadata:
  name: test-lab-cgc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-cgc
  namespace: test-lab-cgc
  labels:
    app: backend-nest-test-cgc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-cgc
  template:
    metadata:
      labels:
        app: backend-nest-test-cgc
    spec:
      containers:
      - name: backend-nest-test-cgc
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-cgc
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
--- 
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-test-cgc-svc
  namespace: test-lab-cgc
  labels:
    app: backend-nest-test-cgc-svc
spec:
  selector: 
    app: backend-nest-test-cgc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-test-cgc
  namespace: test-lab-cgc
spec:
  ingressClassName: nginx
  rules:
  - host: cgctest.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-nest-test-cgc-svc
            port:
              number: 80